id: hashicorp-vault-application
kind: node
logo:
  type: url
  # Vault Community from https://www.hashicorp.com/en/brand/hcp-product-logos
  value: logo/vault/Vault-LogoMark_onLight.svg
  valueDark: logo/vault/Vault-LogoMark_onDark.svg
colors:
  light:
    fill: '#e7f1fa'
    stroke: '#0066cc'
    text: '#151515'
  dark:
    fill: '#1b3a55'
    stroke: '#92c5f9'
    text: '#f0f0f0'
font:
  family: 'RedHatText, Overpass, sans-serif'
  size: 12
